print("==============================") 
print("= NAMA    : Fery Affandi      ") 
print("= NIM     : 312010018         ") 
print("= KELAS   : TI.20 A.1         ") 
print("==============================") 

print("Please enter your full name : Fery Affandi") 
fullname=input()
print("Please enter nickname : Fery")
nickname=input()
print("Please enter your NPM : 312010018")
npm=input()
print("Please enter place of birth : Bogor")
pob=input()
print("Please enter date of birth : 27")
date=input()
print("Please enter your month of birth : February")
month=input()
print("Please enter year of birth : 2001")
year=input()
print("Please enter your phone number : 087719312053")
phone=input()
print("Please enter your address : Perumahan Bumi Pesanggrahan Ciriung")
address=input()

dob=input("2020-year")

print("\n\n Assalamu'alaikum. ")
print("f\n Let me introduce my self, my name is {Fery Affandi}, but you can call me {Fery}, my NPM {312010018}, I was born in {Bogor} and iam {2020} years old, I am very glad if you want to invite my house in {Perumahan Bumi Pesanggrahan Ciriung}, So don't forget to call me before with the number {087719312053}, \n\n Thanks you very much ")